### ISSUE TITLE
encfs from development branch: Switch to latest encfs?

### ISSUE THREAD

**Issue by Aikhjarto** [safeapp/safe#68]
I expirenced the same problem as #16 and digged in a bit.
IMHO the enfs version branched here is an older development version as pointed out by the developer of encfs here: https://github.com/vgough/encfs/issues/98
Are there any plans to use the latest version of encfs in the safe app? Or will the app stick with the development branch?

**Comment by rianhunter** [comment]
Hi yes, I haven't merged in the latest encfs dev for a while. I'm not 100% sure because I'm not a Git expert but this may be a good amount of work since Safe's EncFS checkout derives from a different "svn->git" conversion than the official one on GitHub.

Safe 2.0 will not rely on EncFS, it will use a simpler and more secure file-system encryption scheme. Safe 2.0 will still allow backwards compatibility with EncFS, however, but since EncFS 2.x is essentially vaporware at this point, it will revert back to the EncFS 1.x branch.
